use_frameworks!

platform :ios, '9.0'

target 'TRUNetworking_Example' do
  pod 'TRUNetworking', :path => '../'

  target 'TRUNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
